---
abstract: 'Wrapper module for aws-cli'
author:
  - 'HIROSE Masaaki <hirose31 _at_ gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AWS-CLIWrapper
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  IPC::Cmd: 0
  JSON: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hirose31/AWS-CLIWrapper.git
version: 0.01
